!!it.unibo.model.level.loader.skeleton.ArenaSkeletonImpl
lives: 3
width: 100
height: 100
padSkeleton:
  x: 20
  y: 10
brickSkeletonSet:
  - x: 1
    y: 1
    type: "BLUE"
  - x: 2
    y: 2
    type: "RED"
  - x: 1
    y: 4
    type: "GREEN"
