!!it.unibo.model.level.loader.skeleton.level.LevelSkeletonImpl
lives: 3
width: 100
height: 100
pad:
    x: 50
    y: 80
balls:
  - x: 50
    y: 70
    paceX: 20
    paceY: 10
    ballType: "NORMAL"
    id: 1
bricks:
  - x: 40
    y: 10
    type: "BLUE"
  - x: 70
    y: 10
    type: "RED"
  - x: 15
    y: 5
    type: "YELLOW"
