!!it.unibo.model.level.loader.skeleton.level.LevelSkeletonImpl
lives: 3
width: 500
height: 560
pad:
    x: 200
    y: 500
balls:
  - x: 240
    y: 300
    paceX: 20
    paceY: 20
    ballType: "NORMAL"
    id: 1
bricks:
  - x: 20
    y: 50
    type: "BLUE"
  - x: 90
    y: 50
    type: "RED"
  - x: 160
    y: 40
    type: "YELLOW"
  - x: 100
    y: 150
    type: "RED"
