!!it.unibo.model.level.loader.skeleton.level.LevelSkeletonImpl
lives: 3
width: 500
height: 560
pad:
    x: 200
    y: 500
balls:
  - x: 240
    y: 400
    paceX: -20
    paceY: -10
    ballType: "NORMAL"
    id: 1
bricks:
  - x: 20
    y: 10
    type: "BLUE"
  - x: 90
    y: 10
    type: "RED"
  - x: 160
    y: 5
    type: "YELLOW"
  - x: 100
    y: 50
    type: "RED"
